LogLevel warn
Listen /run/cups/cups.sock
Browsing Off
WebInterface No
DefaultAuthType Basic
PreserveJobHistory Yes
PreserveJobFiles No
MaxJobs 500
MaxLogSize 1048576
<Location />
  Order allow,deny
  Allow from all
</Location>
<Location /admin>
  Order allow,deny
  Allow from all
</Location>
<Policy default>
  <Limit All>
    Order allow,deny
    Allow from all
  </Limit>
</Policy>
